{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% include '_include/messages.phtml' %}
    {% !empty($user->avatar) ? $avatar = $user->avatar : $avatar = 'no-avatar.png'; %}
    <!-- Breadcrumb -->
    <section class="container">
        <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 small">
                <li class="breadcrumb-item"><a href="{{ $this->path() }}" class="link-secondary">Strona główna</a></li>
                <li class="breadcrumb-item active">Konto użytkownika - Profil</li>
            </ol>
        </nav>
    </section>
    <!-- Main Content -->
    <main>
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-4">
                    {% include '_include/account_menu.phtml' %}
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Imię i nazwisko</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ $user->fullname }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Adres e-mail</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ $user->email }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Numer telefonu</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ $user->phone }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Strona internetowa</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ $user->website }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Biografia</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ $user->biography }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col dbm-form-primary">
                                    <p><a href="{{ $this->path('account/profileChange') }}" class="btn btn-primary dbm-btn-primary text-decoration-none">Przejdź do edycji profilu</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}
