{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% include '_include/messages.phtml' %}
    {% !empty($user->avatar) ? $avatar = $user->avatar : $avatar = 'no-avatar.png'; %}
    <!-- Breadcrumb -->
    <section class="container">
        <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 small">
                <li class="breadcrumb-item"><a href="{{ $this->path() }}" class="link-secondary">Strona główna</a></li>
                <li class="breadcrumb-item active">Konto użytkownika - Zmiana hasła</li>
            </ol>
        </nav>
    </section>
    <!-- Main Content -->
    <main>
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-4">
                    {% include '_include/account_menu.phtml' %}
                </div>
                <div class="col-lg-8">
                    <h1 class="h3">Zmiana hasła</h1>
                    <hr>
                    <form action="{{ $this->path('account/passwordChange') }}" method="POST" class="dbm-form-primary">
                        <div class="mb-3">
                            <label for="fieldPasswordOld" class="form-label">Stare hasło</label>
                            <input type="text" name="dbm_password_old" value="{% if (!empty($form['password_old'])): echo $form['password_old']; endif; %}" class="form-control" id="fieldPasswordOld" placeholder="Stare hasło" required>
                            {% if (!empty($form['error_password_old'])): %}
                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_password_old'] }}</div>
                            {% endif; %}
                        </div>
                        <div class="mb-3">
                            <label for="fieldPassword" class="form-label">Nowe hasło</label>
                            <input type="password" name="dbm_password" class="form-control" id="fieldPassword" placeholder="Nowe hasło" required>
                            {% if (!empty($form['error_password'])): %}
                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_password'] }}</div>
                            {% endif; %}
                        </div>
                        <div class="mb-3">
                            <label for="fieldPasswordRepeat" class="form-label">Powtórz nowe hasło</label>
                            <input type="password" name="dbm_password_repeat" class="form-control" id="fieldPasswordRepeat" placeholder="Powtórz nowe hasło" data-rule-equalTo="#fieldPassword" required>
                            {% if (!empty($form['error_password_repeat'])): %}
                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_password_repeat'] }}</div>
                            {% endif; %}
                        </div>
                        <input type="submit" name="inputSubmit" class="btn btn-primary dbm-btn-primary" value="Zmień hasło">
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock %}
