<?php

/**
 * Application: DbM Framework
 * A lightweight PHP framework for building web applications.
 *
 * @author Artur Malinowski
 * @copyright Design by Malina (All Rights Reserved)
 * @license MIT
 * @link https://www.dbm.org.pl
 */

declare(strict_types=1);

namespace Dbm\Support\Config;

use Lib\Files\FileSystem;
use RuntimeException;

final class ModuleConfigWriter
{
    private string $configPath;

    public function __construct(
        private FileSystem $filesystem,
        ?string $configPath = null
    ) {
        $this->configPath = $configPath ?? BASE_DIRECTORY . '/config/modules.php';
    }

    public function load(): array
    {
        if (!is_file($this->configPath)) {
            return [
                'core' => [],
                'plugin' => [],
                'enabled' => [],
            ];
        }

        $config = require $this->configPath;

        if (!is_array($config)) {
            throw new RuntimeException('Invalid modules.php config.');
        }

        return array_merge(
            ['core' => [], 'plugin' => [], 'enabled' => []],
            $config
        );
    }

    public function addPlugin(string $key, string $class): void
    {
        $config = $this->load();

        $key = strtolower($key);

        $config['plugin'][$key] = $class;

        if (!in_array($key, $config['enabled'], true)) {
            $config['enabled'][] = $key;
        }

        $this->write($config);
    }

    public function addCore(string $key, string $class): void
    {
        $config = $this->load();
        $key = strtolower($key);

        $config['core'][$key] = $class;

        // core zawsze jest enabled
        if (!in_array($key, $config['enabled'], true)) {
            $config['enabled'][] = $key;
        }

        $this->write($config);
    }

    public function enable(string $key): void
    {
        $config = $this->load();
        $key = strtolower($key);

        if (!in_array($key, $config['enabled'], true)) {
            $config['enabled'][] = $key;
            $this->write($config);
        }
    }

    public function disable(string $key): void
    {
        $config = $this->load();
        $key = strtolower($key);

        $config['enabled'] = array_values(
            array_filter(
                $config['enabled'],
                static fn($k) => $k !== $key
            )
        );

        $this->write($config);
    }

    public function write(array $config): void
    {
        $content = <<<PHP
            <?php

            // Application: DbM Framework
            // This file is auto-generated by installer.
            // You may edit it manually if you know what you are doing.

            return [
                // Core modules (always enabled)
                'core' =>
            PHP
    . ConfigFormatter::export($config['core'], 1) . ",\n\n"

    . <<<PHP
            // Plugin modules (can be enabled/disabled)
            'plugin' =>
        PHP
    . ConfigFormatter::export($config['plugin'], 1) . ",\n\n"

    . <<<PHP
            // Enabled plugins
            'enabled' =>
        PHP
    . ConfigFormatter::export(array_values($config['enabled']), 1) . "\n];\n";

        if (is_file($this->configPath)) {
            $this->filesystem->editFile($this->configPath, $content);
            return;
        }

        $this->filesystem->saveFile($this->configPath, $content, 0o644);
    }
}
