{% extends 'base_panel.phtml' %}

{% block content %}
    <?php
        // Form data fields
        !empty($page['file']) ? $formFile = '?file=' . $page['file'] : $formFile = null;
    ?><!-- Page Wrapper -->
    <div id="wrapper">
        {% include '_include/panel_sidebar.phtml' %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                {% include '_include/panel_topbar.phtml' %}
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="d-sm-flex align-items-center justify-content-between">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb bg-transparent">
                                <li class="breadcrumb-item"><h1 class="h3 mb-0 text-gray-800"><a href="<?= $this->path('panel/managePage'); ?>" class="text-dark">Manage pages</a></h1></li>
                                <li class="breadcrumb-item active h3" aria-current="page"><?= $page['header'] ?></li>
                            </ol>
                        </nav>
                        <a href="<?= $this->path('panel/createOrEditPage'); ?>" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm font-weight-bold"><i class="fas fa-plus text-white-50 mr-2"></i>Create page</a>
                    </div>
                    {% include '_include/panel_messages.phtml' %}
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <form action="<?= $this->path('panel/'. $page['action']); ?>" method="POST">
                                <div class="accordion" id="accordionFields">
                                    <div id="collapseFieldsOne" class="collapse collapseOpen" data-parent="#accordionFields">
                                        <?php if (empty($this->requestData('file'))) : ?>
                                        <div class="form-group">
                                            <label for="form_filename"><span class="font-weight-bold">File name</span>, the file name will be used in the website address, optimize the file name for search engines. Example: start with the string 'page-' and then file-name.</label>
                                            <input type="text" name="filename" id="form_filename" class="form-control" placeholder="Provide a file name, start with the string 'page-' and then file-name" value="" minlength="3" maxlength="100" pattern="[a-z\-]+" title="Only lowercase letters (a-z) and a dash (-)." required>
                                        </div>
                                        <?php endif; ?>
                                        <div class="form-group">
                                            <?php if (!empty($page['file'])) echo '<span class="float-right">File name: ' . $page['file'] . '</span>' . "\n"; ?>
                                            <label for="form_keywords"><span class="font-weight-bold">Meta keywords</span>, separated by a comma</label>
                                            <input type="text" name="keywords" id="form_keywords" class="form-control" placeholder="Enter the website keywords" value="<?php if (!empty($fields)) : echo $fields->keywords; endif; ?>" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="form_description" class="font-weight-bold">Meta description</label>
                                            <input type="text" name="description" id="form_description" class="form-control" placeholder="Enter the website description" value="<?php if (!empty($fields)) : echo $fields->description; endif; ?>" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="form_title" class="font-weight-bold">Title and meta title</label>
                                            <input type="text" name="title" id="form_title" class="form-control" placeholder="Enter the website title" value="<?php if (!empty($fields)) : echo $fields->title; endif; ?>" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="formContent" class="font-weight-bold"><span class="mr-2" title="View remaining fields" data-toggle="tooltip" data-placement="top"><i id="iconUpDown" class="fas fa-angle-up text-primary" data-toggle="collapse" data-target="#collapseFieldsOne" aria-expanded="false" aria-controls="collapseFieldsOne"></i></span>HTML content</label>
                                    <textarea name="content" id="formContent" class="form-control" rows="15" onKeyDown="if(event.keyCode===9){var v=this.value,s=this.selectionStart,e=this.selectionEnd;this.value=v.substring(0, s)+'\t'+v.substring(e);this.selectionStart=this.selectionEnd=s+1;return false;}"><?php if (!empty($fields)) : echo $fields->content; endif; ?></textarea>
                                </div>
                                <div class="form-group">
                                    <a href="<?= $this->path('panel/createOrEditPage' . $formFile); ?>" class="btn btn-primary mr-md-2">Reload</a>
                                    <button type="button" id="previewContent" class="btn btn-primary mr-md-2">Preview</button>
                                    <button type="button" class="btn btn-primary mr-md-2" data-toggle="modal" data-target="#imagesModal">Images</button>
                                    <button type="submit" class="btn btn-primary text-uppercase"><?= $page['submit'] ?></button>
                                    <input type="hidden" name="file" value="<?= $page['file'] ?>">
                                </div>
                            </form>
                            <ul>
                                <li>You can use <span class="text-danger">HTML</span> code in content textarea (e.g. &lt;p&gt;, &lt;ul&gt; etc. and &lt;img src=&quot;[URL]images/name.jpg&quot; class=&quot;img-fluid&quot; alt=&quot;Short description of the image&quot;&gt;).</li>
                                <li>You can use <span class="text-danger">[URL]</span> code to add a direct url to the content (e.g. for an image address).</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->
            {% include '_include/panel_footer.phtml' %}
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    {% include '_include/panel_logout.phtml' %}

{% endblock %}

{% block body %}
	<!-- Modal Images -->
	<div id="imagesModal" class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-xl" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title font-weight-bold">Uploaded images</h5>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<div class="table-responsive" style="max-height:245px">
						<table class="table table-striped table-sm">
						<thead class="table-dark">
						<tr>
							<th scope="col" width="5%">#</th>
							<th scope="col">Address url and name</th>
							<th scope="col" width="25%" class="text-right">Action</th>
						</tr>
						</thead>
						<tbody id="rowTable">
						<?php if (!empty($page['images'])): $i=1; ?>
						<?php foreach ($page['images'] as $image): ?>
						<tr id="<?= 'row_id_' . $i; ?>">
							<th scope="row"><?= $i; ?></th>
							<td>
								<div class="dbm-css-tooltip">
									<span class="text-break"><?= '[URL]images/page/photo/' . $image; ?></span>
									<div class="tooltip-body">
										<img src="<?= $this->path('images/page/thumb/' . $image); ?>" class="img-fluid" alt="Insert to content">
									</div>
								</div>
							</td>
							<td class="text-right">
								<button class="btn btn-primary btn-sm setImage" title="Insert" data-text="<?= '[URL]images/page/photo/' . $image; ?>"><i class="fas fa-link"></i></button>
								<button class="btn btn-danger btn-sm ml-md-1 deleteImage" title="Delete" data-fid="<?= $i; ?>" data-file="<?= $image ?>"><i class="fas fa-trash-alt"></i></button>
							</td>
						</tr>
						<?php $i++; ?>
						<?php endforeach; ?>
						<?php else: ?>
						<tr>
							<td colspan="3">You haven not uploaded any image.</td>
						<tr>
						<?php endif; ?>
						</tbody>
						</table>
					</div>
					<div class="mt-1 text-right small">* To reload the list, refresh the page using the &quot;Reload&quot; button.</div>
				</div>
				<div class="modal-footer">
					<h6 class="mr-auto">Add image</h6>
					<div class="w-100">
						<div id="formAlert"></div>
						<form method="post" enctype="multipart/form-data">
							<div class="form-group">
								<div class="input-group">
									<div class="custom-file small-custom-file">
										<input type="file" name="file" id="formFile" class="custom-file-input">
										<label for="formFile" class="custom-file-label small-custom-file-label">Choose file</label>
									</div>
								</div>
							</div>
							<div class="form-group">
								<button type="button" name="submit" class="btn btn-primary float-right" id="uploadImage"><i class="fas fa-upload mr-3"></i>Upload image</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Preview Modal -->
	<div id="previewModal" class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="previewModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-xl" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="previewModalLabel">Page content</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
					<div id="previewBody"></div>
				</div>
				<div class="modal-footer">
					<span class="mr-auto small">* The styles in the preview may differ slightly from what actually appears on the landing page.</span>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
	<!-- Custom JavaScript -->
	<script>
		$(document).ready(function() {
			$('#uploadImage').click(function() {
				$('#formAlert').html('').append('<div class="progress mb-3" style="height:20px;"><div class="progress-bar progress-bar-striped progress-bar-animated bg-info" style="width:100%;" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Please wait. Image loading...</div></div>');

				var params = new FormData();
				var files = $('#formFile')[0].files[0];
				params.append('file', files);
	
				$.ajax({
					type: 'POST',
					url: '<?= $this->path(); ?>panel/ajaxUploadImage',
					data: params,
					contentType: false,
					processData: false,
					success: function(response) {
						if (response != 0) {
							var alert = JSON.parse(response);

							$('#formAlert').html('').append('<div class="alert alert-' + alert['status'] + ' px-2 py-1">' + alert['message'] + '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');

							if (alert['data'] !== undefined) {
								$('#rowTable').prepend('<tr><td class="font-weight-bold text-">#new</td><td colspan="2"><div class="dbm-css-tooltip"><span>[URL]images/page/photo/' + alert['data'] + '</span><div class="tooltip-body"><img src="<?= getenv('APP_URL'); ?>public/images/page/thumb/' + alert['data'] + '" class="img-fluid" alt="Insert to content"></div></div></td></tr>');
								$(".custom-file-label").html('');
							}
						} else {
							alert('JavaScript: An unexpected response error occurred!');
						}
					},
					error: function() {
						alert('JavaScript: An unexpected error occurred!');
					}
				});
			});

			$('.deleteImage').click(function () {
				var fid = $(this).attr("data-fid");
				var file = $(this).attr("data-file");
				var params = 'file=' + file;

				if (confirm('Are you sure you want to delete?')) {
					$.ajax({
						type: "GET",
						url: '<?= $this->path(); ?>panel/ajaxDeleteImage',
						data: params,
						cache: false,
						contentType: false,
						processData: false,
						success: function(response) {
							if (response != 0) {
								var alert = JSON.parse(response);

								$('#row_id_' + fid).fadeOut();
								$('#formAlert').html('').append('<div class="alert alert-' + alert['status'] + ' px-2 py-1">' + alert['message'] + '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
							} else {
								alert('JavaScript: An unexpected response error occurred!');
							}
						},
						error: function() {
							alert('JavaScript: An unexpected error occurred!');
						}
					});

					return false;
				}
			});

			$('.setImage').click(function() {
				const textToInsert = $(this).attr("data-text");
				const textarea = $("#formContent")[0];
				const startPos = textarea.selectionStart;
				const endPos = textarea.selectionEnd;
				const currentText = textarea.value;

				if (startPos === null || startPos === 0 && endPos === 0) {
					textarea.value = currentText + textToInsert;
				} else {
					const beforeCursor = currentText.substring(0, startPos);
					const afterCursor = currentText.substring(endPos);

					textarea.value = beforeCursor + textToInsert + afterCursor;
					textarea.selectionStart = textarea.selectionEnd = startPos + textToInsert.length;
				}

				textarea.focus();

				$('#imagesModal').modal('hide');
			});

			$("#previewContent").click(function () {
                var code = $("#formContent").val();

				if (code.length === 0) {
					result = '<div class="alert alert-info">The content is empty! Add content, use HTML tags and the Bootstrap library to format the text.</div>';
				} else {
					result = code.replace('[URL]', '<?= getenv('APP_URL'); ?>');
				}

                $("#previewBody").html(result);
				$('#previewModal').modal('show'); 

                return false;
            });

			$("#iconUpDown").click(function() {
				if (!$(this).hasClass('fa-angle-up')) {
					$('.fa-angle-up').toggleClass("fa-angle-up").toggleClass("fa-angle-down");
				}
				
				$(this).toggleClass("fa-angle-up").toggleClass("fa-angle-down");
			});

			$('[data-toggle="tooltip"]').tooltip();
		});

		$(".custom-file-input").on("change", function() {
			var fileName = $(this).val().replace(/^.*[\\\/]/, '');
			$(this).siblings(".custom-file-label").addClass("selected").html(fileName);
		});

		$('#collapseOne').show();
		$('#collapseOne a:nth-child(3)').addClass("active");

		<?php if (!empty($page['accordion']) && $page['accordion'] === true) : ?>
			$('.collapseOpen').eq(0).collapse('show');
		<?php endif; ?>
        
	</script>

{% endblock %}
