{% extends 'base_panel.phtml' %}

{% block head %}
	<!-- Head: Error Logs -->
{% endblock %}

{% block content %}<!-- Page Wrapper -->
    <div id="wrapper">
        {% include '_include/panel_sidebar.phtml' %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                {% include '_include/panel_topbar.phtml' %}
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb bg-transparent">
                                <li class="breadcrumb-item active" aria-current="page"><h1 class="h3 mb-0 text-gray-800">Error logs</h1></li>
                            </ol>
                        </nav>
                    </div>
                    <!-- Content Row -->
                    <div class="row">
                        <!-- Area Chart -->
                        <div class="col-lg-5">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 text-primary font-weight-bold">Log files</h6>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                    <div class="overflow-auto" style="max-height:600px;">
                                        <ul class="list-group">
                                            {% foreach ($files as $file): %}
                                            <li class="list-group-item d-flex justify-content-between align-items-center px-1 py-0">
                                                <a href="{{ $this->path('panel/toolsLogs') }}?file={{ $file }}" class="text-info text-decoration-none">{{ $file }}</a>
                                                <a href="{{ $this->path('panel/toolsLogs') }}?action=delete&amp;file={{ $file }}" class="badge badge-danger badge-pill">Delete</a>
                                            </li>
                                            {% endforeach; %}

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Pie Chart -->
                        <div class="col-lg-7">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 text-primary font-weight-bold">Preview{% if (!empty($_GET['file'])): %}: <span class="font-weight-normal">{{ $_GET['file'] }}</span>{% endif; %}</h6>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                    <div class="overflow-auto" style="max-height:600px;">
                                        <p>{{ $preview }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->
            {% include '_include/panel_footer.phtml' %}
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    {% include '_include/panel_logout.phtml' %}
{% endblock %}
