{% extends 'base_panel.phtml' %}

{% block head %}
	<!-- Style Head Custom Datatables -->
    <link href="<?= $this->path('admin/vendor/datatables/dataTables.bootstrap4.min.css') ?>" rel="stylesheet">
{% endblock %}

{% block content %}<!-- Page Wrapper -->
    <div id="wrapper">
        {% include '_include/panel_sidebar.phtml' %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                {% include '_include/panel_topbar.phtml' %}
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb bg-transparent">
                                <li class="breadcrumb-item active" aria-current="page"><h1 class="h3 mb-0 text-gray-800">Manage gallery</h1></li>
                            </ol>
                        </nav>
                        <a href="<?= $this->path('panel/addOrEditPhoto') ?>" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm font-weight-bold"><i class="fas fa-plus text-white-50 mr-2"></i>Add photo</a>
                    </div>
                    {% include '_include/panel_messages.phtml' %}
                    <!-- DataTales -->
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="dataTableOne" class="table table-striped" width="100%" cellspacing="0">
                                    <thead class="table-dark">
                                        <tr>
                                            <th width="5%">ID</th>
                                            <th width="10%" class="noSort">Photo</th>
                                            <th width="20%">Title</th>
                                            <th width="31%">Description</th>
                                            <th width="5%">Status</th>
                                            <th width="12%">Created</th>
                                            <th width="12%">Modified</th>
                                            <th width="5%" class="text-right noSort">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($gallery as $item): ?>
                                        <tr>
                                            <td class="font-weight-bold"><?= $item->id ?></td>
                                            <td><img src="<?= $this->path('images/gallery/thumb/') . $item->filename; ?>" alt="" style="width:30px" data-toggle="tooltip" data-placement="top" data-html="true" title="<img src='<?= $this->path('images/gallery/thumb/') . $item->filename; ?>' class='img-fluid'>"></td>
                                            <td class="font-weight-bold"><?= $item->title ?></td>
                                            <td><?= $item->description ?></td>
                                            <td><?php ($item->status == true) ? $modified = '<span class="badge badge-success">Active</span>' : $modified = '<span class="badge badge-danger">Inactive</span>'; echo $modified; ?></td>
                                            <td><?= $item->created ?></td>
                                            <td><?php ($item->modified === null) ? $modified = '<span class="badge badge-secondary">Null</span>' : $modified = $item->modified; echo $modified; ?></td>
                                            <td class="text-right"><div class="btn-group"><button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-ellipsis-h mr-1"></i></button><div class="dropdown-menu dropdown-menu-right"><a href="<?= 'addOrEditPhoto?id=' . $item->id ?>" class="dropdown-item text-primary" type="button">Edit</a><button type="button" class="dropdown-item text-danger deletePhoto" data-toggle="modal" data-target=".deleteModal" data-id="<?= $item->id ?>">Delete</button></div></div></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->
            {% include '_include/panel_footer.phtml' %}
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    {% include '_include/panel_logout.phtml' %}
{% endblock %}

{% block body %}
    <!-- Modal Delete -->
    <div id="deleteModal" class="modal fade deleteModal" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="deleteModalLabel">
    	<div class="modal-dialog" role="document">
        	<div class="modal-content">
            	<div class="modal-header border-0">
                	<h5 class="modal-title" id="deleteModalLabel"><i class="fas fa-trash-alt mr-3 text-danger"></i>Confirm Delete</h5>
                	<button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            	</div>
            	<div class="modal-body">
					<p class="font-weight-bold mb-2">Are you sure you want to delete this?</p>
				</div>
            	<div class="modal-footer border-0">
                	<button type="button" class="btn btn-light text-muted" data-dismiss="modal">Cancel</button>
					<button type="button" id="photoDelete" class="btn btn-danger px-4 ml-2" data-dismiss="modal" data-file="">Delete</button>
            	</div>
        	</div>
    	</div>
	</div>
	<script>
		$(document).ready(function() {
			$('#photoDelete').click(function () {
				var id = $(this).attr("data-id");
				var params = 'id=' + id;
				
				$.ajax({
					type: "GET",
					url: '<?php echo APP_PATH; ?>panel/ajaxDeletePhoto',
					data: params,
					success: function(response) {
						if (response != 0) {
							var alert = JSON.parse(response);
							window.location.replace("<?php echo APP_PATH; ?>panel/manageGallery?action=delete" + "&status=" + alert['status'] + '&message=' + alert['message']);
						} else {
							alert('JavaScript: An unexpected response error occurred!');
						}
					},
					error: function(response) {
						alert('JavaScript: An unexpected error occurred!');
					}
				});
			});

			$('.deletePhoto').click(function () {
				var id = $(this).attr("data-id");
				$('#photoDelete').attr("data-id", id);
			});

			$('#collapseThree').show();
			$('#collapseThree a:nth-child(2)').addClass("active");

            $(function () {
                $('[data-toggle="tooltip"]').tooltip();
            })
		});
	</script>
	<!-- DataTables.net -->
    <script src="../admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="../admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#dataTableOne').dataTable({
                pageLength: 10,
                columnDefs: [{
                    targets: 'noSort',
                    orderable: false,
                }],
				order: [[0, 'desc']],
            });
        });
    </script>
{% endblock %}
