                    <!-- Box right images -->
                    <div class="p-4">
                        <h4 class="fst-italic">Images</h4>
                        <p><img src="<?= $this->path('images/page/photo/post-graphics.jpg') ?>" class="img-fluid" alt="..."></p>
                        <p><img src="<?= $this->path('images/page/photo/post-social-media.jpg') ?>" class="img-fluid" alt="..."></p>
                    </div>
