    <!-- Header -->
    <h1 class="visually-hidden"><?= trans('website.name') ?></h1>
    <header class="navbar navbar-expand-md shadow py-3 dbm-header">
        <nav class="container-md flex-wrap flex-md-nowrap position-relative" aria-label="<?= trans('navbar.main_navigation') ?>">
            <a href="<?= path() ?>" class="navbar-brand text-white text-decoration-none"><img src="<?= path('images/logo.png') ?>" class="img-fluid align-middle me-3" alt="<?= trans('website.name') ?>"><h2 class="d-inline"><?= trans('index.header') ?></h2></a>
            <div class="position-absolute top-0 end-0">
                <?= htmlLanguage(path()) ?>
            </div>
        </nav>
    </header>
