<!-- Navigation Basic List -->
                    <ul>
                        <li><a href="{{ $this->path() }}">Home</a></li>
                        <li><a href="#services">Services</a></li>
                        <li><a href="#portfolio">Portfolio</a></li>
                        <li><a href="#contact">Contact</a></li>
                        <li class="dropdown">
                            <a href="#">Blog <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                            <ul>
                                <li><a href="#">Category name</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#"><i class="bi bi-person fs-5 me-2 d-none d-xl-block"></i>Your account <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                            <ul>
                                <li><a href="#">Log in to your account</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" role="button"><img src="{{ $this->asset('images/lang/en.png') }}" alt="EN"> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                            <ul class="dbm-list-language-one">
                                <li class="dropdown-item active"><a href="{{ $this->path() }}?lang=OFF" class="d-block"><img src="{{ $this->asset('images/lang/en.png') }}" alt="EN" class="me-2">EN</a></li>
                            </ul>
                        </li>
                    </ul>
