<!-- Navigation Footer Basic -->
                    <ul>                                                                                            
                        <li><i class="bi bi-chevron-right"></i><a href="#">Home</a></li>                                                                                            
                        <li><i class="bi bi-chevron-right"></i><a href="#">About us</a></li>                                                                                        
                        <li><i class="bi bi-chevron-right"></i><a href="#">Contact</a></li>                                                                                        
                        <li><i class="bi bi-chevron-right"></i><a href="#">Terms of use</a></li>                        
                    </ul>
