<!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a href="<?= $this->path() ?>" class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon ?rotate-n-15"><i class="fas fa-home"></i></div>
                <div class="sidebar-brand-text ml-2">DbM Framework</div>
            </a>
            <hr class="sidebar-divider my-0">
            <li class="nav-item active">
                <a class="nav-link" href="<?= $this->path('panel') ?>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <div class="sidebar-heading">Interfejs</div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"><i class="fas fa-fw fa-folder"></i><span>Pages on text files</span></a>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">
                    <div class="collapse-inner bg-white rounded py-2">
                        <h6 class="collapse-header">Pages on text files</h6>
                        <a class="collapse-item" href="<?= $this->path('panel/managePage') ?>">Manage pages</a>
                        <a class="collapse-item" href="<?= $this->path('panel/createOrEditPage') ?>">Create page</a>
                    </div>
                </div>
                <a class="nav-link collapsed pt-0" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseOne"><i class="fas fa-fw fa-blog"></i><span>Blog and articles</span></a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="collapse-inner bg-white rounded py-2">
                        <h6 class="collapse-header">Blog and articles</h6>
                        <a class="collapse-item" href="<?= $this->path('panel/manageBlog') ?>">Manage blog</a>
                        <a class="collapse-item" href="<?= $this->path('panel/createOrEditBlog') ?>">Create article</a>
                        <a class="collapse-item" href="<?= $this->path('panel/manageBlogSections') ?>">Manage blog sections</a>
                        <a class="collapse-item" href="<?= $this->path('panel/createOrEditBlogSection') ?>">Create section</a>
                    </div>
                </div>
            </li>
            <hr class="sidebar-divider">
            <div class="sidebar-heading">Tools</div>
            <li class="nav-item">
                <a class="nav-link" href="<?= $this->path('panel/toolsLogs') ?>"><i class="fas fa-fw fa-exclamation-triangle"></i><span>Error logs</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link pt-0" href="http://localhost/phpmyadmin/" target="_blank"><i class="fas fa-fw fa-database"></i><span>SQL Database</span></a>
            </li>
            <hr class="sidebar-divider d-none d-md-block">
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="<?= $this->path('admin/img/undraw_rocket.svg') ?>" alt="...">
                <p class="text-center mb-2"><strong>DbM Framework</strong> check if an upgrade is available.</p>
                <a href="https://dbm.org.pl" class="btn btn-success btn-sm" target="_blank">Upgrade</a>
            </div>
        </ul>
        <!-- End of Sidebar -->
