<?php use App\Config\ConstantConfig; ?>
{% extends 'base.phtml' %}

{% block head %}
    <!-- Lightbox CSS -->
    <link href="{{ $this->path('assets/vendor/lightbox/style.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% include '_include/messages.phtml' %}
<!-- Breadcrumb -->
    <section class="container">
        <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 small">
                <li class="breadcrumb-item active">Photo gallery</li>
            </ol>
        </nav>
    </section>
    <!-- Main Content - Blog index -->
    <main>
        <div class="container">
            <div id="loadDataGallery" class="row row-cols-1 row-cols-md-3 g-4 mb-4 lightboxGalleryGrid" data-masonry='{ "percentPosition": true }'>
                {% foreach($gallery as $item): %}
                
                    <div class="col text-center">
                        <a class="gallery-item" href="{{ $this->path('images/gallery/photo/') . $item->filename; }}">
                            <img src="{{ $this->path('images/gallery/thumb/') . $item->filename; }}" class="img-fluid" alt="{{ $item->title }}">
                        </a>
                    </div>
                {% endforeach; %}

            </div>
        </div>
        <div class="container" id="loadMessageContainer">
		    <div class="row text-center p-2">
                <div id="loadDataMessage"></div>
            </div>
        </div>
    </main>

{% endblock %}

{% block body %}
    <!-- Lightbox JS & Modal -->
    <script src="{{ $this->path('assets/vendor/lightbox/script.js') }}" id="?jsLightbox"></script>
    <div class="modal fade lightbox-modal" id="lightbox-modal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered modal-fullscreen">
            <div class="modal-content">
                <button type="button" class="btn-fullscreen-enlarge" aria-label="Enlarge fullscreen">
                    <svg class="bi"><use href="#enlarge"></use></svg>
                </button>
                <button type="button" class="btn-fullscreen-exit d-none" aria-label="Exit fullscreen">
                    <svg class="bi"><use href="#exit"></use></svg>
                </button>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="modal-body">
                    <div class="lightbox-content">
                        <!-- JS content here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Masonry with the Bootstrap grid system for images view -->
    <script src="{{ $this->path('assets/js/masonry.pkgd.min.js') }}"></script>
    <!-- AJAX Load Data -->
    <script src="{{ $this->path('assets/js/jquery.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            var limit = <?= ConstantConfig::GALLERY_INDEX_ITEM_LIMIT; ?>;
            var start = <?= ConstantConfig::GALLERY_INDEX_ITEM_LIMIT; ?>;
            var action = 'inactive';

            function loadDataToBox(limit, start) {
                $.ajax({
                    method: 'POST',
                    url: '<?= $this->path(); ?>gallery/ajaxLoadData',
                    data: {limit:limit, start:start},
                    cache: false,
                    success: function(data) {
                        $('#loadDataGallery').append(data);

                        if (data == '') {
                            $('#loadDataMessage').html('<span class="p-2 text-info">No data found.</span>');
                            $('#loadMessageContainer').fadeOut(1000);
                            action = 'active';
                        } else {
                            $('#loadDataMessage').html('<img src="<?= $this->path('images/loading.gif'); ?>" width="30" alt="Loading">');
                            action = "inactive";
                        }
                    }
                });
            }
            
            if (action == 'inactive') {
                action = 'active';
                loadDataToBox(limit, start);
            }

            $(window).scroll(function() {
                if (($(window).scrollTop() == $(document).height() - $(window).height()) && (action == 'inactive')) {
                    action = 'active';
                    start = start + limit;

                    setTimeout(function(){
                        loadDataToBox(limit, start);
                    }, 1000);
                }
            });
        });
    </script>
{% endblock %}
