{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% if (!empty($article)): %}

    <!-- Breadcrumb -->
    <section class="container">
        <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 small">
                <li class="breadcrumb-item"><a href="{{ $this->path() }}" class="link-secondary">Blog</a></li>
                <li class="breadcrumb-item"><a href="{{ $this->path('blog/sections') }}" class="link-secondary">Article categories</a></li>
                <li class="breadcrumb-item"><a href="{{ $this->path('blog/'.$this->linkSEO('sec', $article->sid, $article->section_name)) }}" class="link-secondary">{{ $article->section_name }}</a></li>
                <li class="breadcrumb-item active">{{ $article->page_header }}</li>
            </ol>
        </nav>
    </section>
    <!-- Main Content - Blog article -->
    <main class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="pb-4 mb-4 fst-italic border-bottom">{{ $article->page_header }}</h1>
                <article class="blog-post mb-3">
                    {{ $this->outputHTML($article->page_content) }}
    			</article>
            </div>
            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    {% include '_include/box_right_about.phtml' %}
                    {% include '_include/box_right_images.phtml' %}
                </div>
    		</div>
        </div>
    </main>

    {% else: %}

    <!-- Main Content - Blog article error -->
    <main class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">An unexpected error occurred, required data is missing.</div>
            </div>
        </div>
    </main>
    
    {% endif; %}
{% endblock %}
