{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}

    <!-- Breadcrumb -->
    <section class="container">
        <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 small">
                <li class="breadcrumb-item"><a href="{{ $this->path() }}" class="link-secondary">Blog</a></li>
                <li class="breadcrumb-item active">Article categories</li>
            </ol>
        </nav>
    </section>
    <!-- Main Content - Blog sections -->
    <main class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    {% foreach($sections as $item): %}
                        {% ($item->image_thumb != null) ? $image = $item->image_thumb : $image = 'no-image.jpg'; %}

                    <div class="col-md-6 d-flex align-items-stretch mb-4 aos-init aos-animate" data-aos="zoom-in" data-aos-delay="200">
                        <div class="dbm-box-image">
                            <div class="image">
                                <img src="{{ $this->path('images/blog/category/thumb/' . $image) }}" alt="{{ $this->output($item->section_name) }}" class="img-fluid img-thumbnail" style="width:100%;max-height:215px">
                            </div>
                            <h4 class="title"><a href="{{ $this->path('blog/'.$this->linkSEO('sec', $item->id, $item->section_name)) }}" title="{{ $this->output($item->section_name) }}">{{ $this->truncate($item->section_name, 40) }}</a></h4>
                            <p class="description">{{ $this->truncate($item->section_description, 300) }}</p>
                        </div>
                    </div>
                    {% endforeach; %}

                </div>
            </div>
            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    {% include '_include/box_right_about.phtml' %}
                    {% include '_include/box_right_images.phtml' %}
                </div>
            </div>
        </div>
    </main>

{% endblock %}
