    <?php
        // Navigation
        include('../templates/_include/navigation.phtml');
        // Flash messages
        include('../templates/_include/messages.phtml');
    ?>
<!-- Main Content - Blog sections -->
    <main class="container">
        <div class="row">
            <div class="col">
                <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 small">
                        <li class="breadcrumb-item"><a href="<?= path() ?>" class="link-secondary">Blog</a></li>
                        <li class="breadcrumb-item active">Article categories</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <?php 
                        foreach($sections as $object) {
                            ($object->image_thumb != null) ? $image = $object->image_thumb : $image = 'no-image.jpg';
                            $link = linkSEO('sec', $object->id, $object->section_name);
                    ?>

                    <div class="col-md-6 d-flex align-items-stretch mb-4 aos-init aos-animate" data-aos="zoom-in" data-aos-delay="200">
                        <div class="dbm-box-image">
                            <div class="image">
                                <img src="<?= path('images/blog/category/thumb/' . $image) ?>" alt="<?= output($object->section_name) ?>" class="img-fluid img-thumbnail" style="width:100%;max-height:215px">
                            </div>
                            <h4 class="title"><a href="<?= $link ?>" title="<?= output($object->section_name) ?>"><?= truncate($object->section_name, 40) ?></a></h4>
                            <p class="description"><?= truncate($object->section_description, 300) ?></p>
                        </div>
                    </div>
                    <?php }; ?>

                </div>
            </div>
            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <?php
                        // Box right about
                        include('../templates/_include/box_right_about.phtml');
                        // Box right about
                        include('../templates/_include/box_right_images.phtml');
                    ?>
                </div>
            </div>
        </div>
    </main>
