{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}

    <!-- Breadcrumb -->
    <section class="container">
        <nav class="bg-light rounded-3 px-3 py-2 mb-4" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 small">
                <li class="breadcrumb-item"><a href="{{ $this->path() }}" class="link-secondary">Blog</a></li>
                <li class="breadcrumb-item"><a href="{{ $this->path('blog/sections') }}" class="link-secondary">Article categories</a></li>
                <li class="breadcrumb-item active">{% if (!empty($section)): %}{{ $section['section_name'] }}{% endif; %}</li>
            </ol>
        </nav>
    </section>
    <!-- Main Content - Blog section -->
    <main class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    {% if (is_array($articles)) : %}
                    {% foreach($articles as $item) : %}
                        {% ($item->image_thumb != null) ? $image = $item->image_thumb : $image = 'no-image.jpg'; %}
                    
                    <div class="col-md-6 d-flex align-items-stretch mb-4 aos-init aos-animate" data-aos="zoom-in" data-aos-delay="200">
                        <div class="dbm-box-image">
                            <div class="image">
                                <img src="{{ $this->path('images/blog/thumb/' . $image) }}" alt="{{ $this->output($item->page_header) }}" class="img-fluid img-thumbnail" style="width:100%;max-height:215px">
                            </div>
                            <h4 class="title"><a href="{{ $this->path($this->linkSEO('art', $item->aid, $item->page_header)) }}" title="{{ $this->output($item->page_header) }}">{{ $this->truncate($item->page_header, 40) }}</a></h4>
                            <h6 class="details"><span class="me-1">By</span><a href="{{ $this->path($this->linkSEO('user', $item->uid)) }}" class="link-dark">{{ $item->fullname }}</a><span class="mx-1">in</span><a href="{{ $this->path('blog/'.$this->linkSEO('sec', $item->sid, $item->section_name)) }}" class="link-dark">{{ $item->section_name }}</a></h6>
                            <p class="description">{{ $this->truncate($item->page_content, 300) }}</p>
                        </div>
                    </div>
                    {% endforeach; %}
                    {% else: %}

                    <div class="col-md-12">
                        <div class="alert alert-info">{{ $articles }}</div>
                    </div>
                    {% endif; %}

                </div>
            </div>
            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    {% include '_include/box_right_about.phtml' %}
                    {% include '_include/box_right_images.phtml' %}
                </div>
            </div>
        </div>
    </main>

{% endblock %}
