{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% include '_include/messages.phtml' %}
<!-- Main Content -->
    <section class="h-100 dbm-form-gradient-1">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 mx-md-4">
                                    <form action="{{ $this->path('login/signin') }}" method="POST" class="dbm-form-primary">
                                        <h4 class="mt-1 mb-4 pb-1">{{ $this->trans('login.header') }}</h4>
                                        <div class="form-outline mb-3">
                                            <label class="form-label mb-1 ?d-none" for="form_login">{{ $this->trans('login') }}</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic_addon_1"><i class="bi bi-person"></i></span>
                                                <input type="text" name="dbm_login" value="{% if (!empty($form['login'])): echo $form['login']; endif; %}" id="form_login" class="form-control" placeholder="{{ $this->trans('username_or_email') }}" required>
                                            </div>
                                            {% if (!empty($form['error_login'])): echo '<div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>' . $form['error_login'] . '</div>' . "\n"; endif; %}
                                        </div>
                                        <div class="form-outline mb-3">
                                            <label class="form-label mb-1 ?d-none" for="form_password">{{ $this->trans('password') }}</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic_addon_2"><i class="bi bi-lock"></i></span>
                                                <input type="password" name="dbm_password" value="" id="form_password" class="form-control" placeholder="{{ $this->trans('password') }}" required>
                                            </div>
                                            {% if (!empty($form['error_password'])): echo '<div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>' . $form['error_password'] . '</div>' . "\n"; endif; %}
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col d-flex justify-content-center">
                                                <div class="form-check">
                                                    <input type="checkbox" name="dbm_remember_me" id="form_remember_me" value="checked" class="form-check-input">
                                                    <label class="form-check-label" for="form_remember_me">{{ $this->trans('remember_me') }}</label>
                                                </div>
                                            </div>
                                            <div class="col d-flex justify-content-center">
                                                <a href="{{ $this->path('reset') }}" class="text-decoration-none">{{ $this->trans('forgot_password') }}</a>
                                            </div>
                                        </div>
                                        <div class="d-grid gap-2 mb-3 text-center">
                                            <button type="submit" class="btn btn-primary btn-block text-uppercase fw-bold">{{ $this->trans('sign_in') }}</button>
                                            <input type="hidden" name="csrf_token" value="{% if (!empty($form['token'])): echo $form['token']; endif; %}">
                                        </div>
                                        <div class="d-flex align-items-center justify-content-center mb-3">
                                            <p class="mb-0">{{ $this->trans('dont_have_account') }} <a href="{{ $this->path('register') }}" class="text-decoration-none">{{ $this->trans('register_new') }}</a></p>
                                        </div>
                                        <div class="d-flex align-items-center justify-content-center mb-3 dbm-divider-1">
                                            <p class="text-center fw-bold mx-3 mb-0 text-muted">{{ $this->trans('or') }}</p>
                                        </div>
                                        <div class="d-flex align-items-center justify-content-center">
                                            <a class="btn dbm-btn-facebook" href="#!" role="button"><i class="bi bi-facebook me-2"></i>{{ $this->trans('continue_with_facebook') }}</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center position-relative dbm-background-1">
                                {% include '_include/authentication_information.phtml' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
