{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% include '_include/messages.phtml' %}
<!-- Main Content -->
    <section class="h-100 dbm-form-gradient-1">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 mx-md-4">
                                    <form action="{{ $this->path('register/signup') }}" method="POST" class="dbm-form-primary">
                                        <h4 class="mt-1 mb-4 pb-1">{{ $this->trans('register.header') }}</h4>
                                        <div class="form-outline mb-2">
                                            <label class="form-label mb-1" for="form_login">{{ $this->trans('username') }}</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic_addon_3"><i class="bi bi-person"></i></span>
                                                <input type="text" name="dbm_login" value="{% if (!empty($form['login'])): echo $this->sanitize($form['login']); endif; %}" id="form_login" class="form-control" placeholder="{{ $this->trans('your_login') }}" minlength="2" maxlength="30" required>
                                            </div>
                                            {% if (!empty($form['error_login'])): %}
                                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_login'] }}</div>
                                            {% endif; %}
                                        </div>
                                        <div class="form-outline mb-2">
                                            <label class="form-label mb-1" for="form_email">{{ $this->trans('email') }}</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic_addon_1">@</span>
                                                <input type="email" name="dbm_email" value="{% if (!empty($form['email'])): echo $this->sanitize($form['email']); endif; %}" id="form_email" class="form-control" placeholder="{{ $this->trans('email_address') }}" required>
                                            </div>
                                            {% if (!empty($form['error_email'])): %}
                                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_email'] }}</div>
                                            {% endif; %}
                                        </div>
                                        <div class="form-outline mb-2">
                                            <label class="form-label mb-1" for="form_password">{{ $this->trans('password') }}</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic_addon_2"><i class="bi bi-lock"></i></span>
                                                <input type="password" name="dbm_password" id="form_password" class="form-control" placeholder="{{ $this->trans('password') }}" required>
                                            </div>
                                            {% if (!empty($form['error_password'])): %}
                                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_password'] }}</div>
                                            {% endif; %}
                                        </div>
                                        <div class="form-outline mb-2">
                                            <label class="form-label mb-1" for="form_confirmation">{{ $this->trans('repeat_password') }}</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic_addon_2"><i class="bi bi-lock"></i></span>
                                                <input type="password" name="dbm_confirmation" id="form_confirmation" class="form-control" placeholder="{{ $this->trans('password') }}" data-rule-equalTo="#form_password" required>
                                            </div>
                                            {% if (!empty($form['error_confirmation'])): %}
                                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_confirmation'] }}</div>
                                            {% endif; %}
                                        </div>
                                        <div class="d-grid gap-2 mb-2 mt-4 text-center">
                                            <button type="submit" class="btn btn-primary btn-block text-uppercase fw-bold dbm-btn-primary">{{ $this->trans('create_account') }}</button>
                                            <input type="hidden" name="csrf_token" value="{% if (!empty($form['token'])): echo $form['token']; endif; %}">
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center position-relative dbm-background-1">
                                {% include '_include/authentication_information.phtml' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
