{% extends 'base.phtml' %}

{% block content %}
    {% include '_include/navigation.phtml' %}
    {% include '_include/messages.phtml' %}
<!-- Main Content -->
    <section class="h-100 dbm-form-gradient-1">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 mx-md-4">
                                    <form action="{{ $this->path('reset/password') }}" method="POST" class="dbm-form-primary">
                                        <h4>{{ $this->trans('reset.header') }}</h4>
                                        <p>{{ $this->trans('reset.subheader_create') }}</p>
                                        <div class="mb-3">
                                            <label for="fieldPassword" class="form-label">Nowe hasło</label>
                                            <input type="password" name="dbm_password" class="form-control" id="fieldPassword" placeholder="Nowe hasło" required>
                                            {% if (!empty($form['error_password'])): %}
                                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_password'] }}</div>
                                            {% endif; %}
                                        </div>
                                        <div class="mb-3">
                                            <label for="fieldPasswordRepeat" class="form-label">Powtórz nowe hasło</label>
                                            <input type="password" name="dbm_password_repeat" class="form-control" id="fieldPasswordRepeat" placeholder="Powtórz nowe hasło" data-rule-equalTo="#fieldPassword" required>
                                            {% if (!empty($form['error_password_repeat'])): %}
                                                <div class="text-danger small"><i class="bi bi-info-circle-fill me-2 small"></i>{{ $form['error_password_repeat'] }}</div>
                                            {% endif; %}
                                        </div>
                                        <div class="d-grid gap-2 mb-3 text-center">
                                            <button type="submit" class="btn btn-primary btn-block text-uppercase fw-bold">{{ $this->trans('reset_password') }}</button>
                                            <input type="hidden" name="csrf_token" value="{% if (!empty($form['csrf_token'])): echo $form['csrf_token']; endif; %}">
                                            <input type="hidden" name="token" value="{% if (!empty($token)): echo $token; endif; %}">
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center position-relative dbm-background-1">
                                {% include '_include/authentication_information.phtml' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
