<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="Design by Malina">
    <meta name="robots" content="noindex,nofollow">
	<title>{{ $this->trans('meta.title', $data) }}</title>
	<link href="{{ $this->path('images/favicon.png') }}" rel="icon">
	<!-- Stylesheets -->
	<link href="{{ $this->path('admin/vendor/fontawesome-free/css/all.min.css'); }}"  type="text/css" rel="stylesheet">
    <link href="{{ $this->path('admin/css/sb-admin-2.min.css') }}" rel="stylesheet">
	<!-- Stylesheets Custom -->
	<link href="{{ $this->path('admin/css/custom.css') }}" rel="stylesheet">
	<!-- Yield Head - Additions -->{% yield head %}
</head>
<body class="bg-gradient-primary" id="page-top">
	{% yield content %}
	<!-- JavaScript Body -->
	<script src="{{ $this->path('admin/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ $this->path('admin/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ $this->path('admin/js/sb-admin-2.min.js') }}"></script>
	<!-- Yield Body - Additions -->{% yield body %}
</body>
</html>
