<!DOCTYPE html>
<html lang="<?= trans('lang') ?>" class="h-100">
<head>
	<meta charset="<?= trans('charset') ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Design by Malina">
    <meta name="robots" content="<?= trans('meta.robots') ?>">
    <meta name="keywords" content="<?= trans('meta.keywords') ?>">
	<meta name="description" content="<?= trans('meta.description') ?>">
	<title><?= trans('meta.title') ?></title>
	<link href="<?= path('images/favicon.png') ?>" rel="icon">
	<!-- Stylesheets -->
	<link href="<?= path('assets/css/bootstrap.min.css') ?>" rel="stylesheet">
	<link href="<?= path('assets/css/font/bootstrap-icons.css') ?>" rel="stylesheet">
	<!-- Stylesheets Custom -->
	<link href="<?= path('assets/css/custom.css') ?>" rel="stylesheet">
<?php
    // Block Custom Head for the current page in: _include/head_[file_name] (e.g. additional Stylesheet of a given subpage)
     if ($pathHeadInc !== null) {
         include($pathHeadInc);
     }
?>
</head>
<body class="d-flex flex-column h-100">
<?php
    // Header
    include('_include/header.phtml');
    // Block Body Content, view content of the pages; variable $pathViewName is in location: FrameworkClass.php > view()
    include($pathViewName);
    // Footer
    include('_include/footer.phtml');
    // Block Custom Body for the current page in: _include/body_[file_name] (e.g. additional JavaScript of a given subpage)
    if ($pathBodyInc !== null) {
        include($pathBodyInc);
    }
?>
</body>
</html>
